apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    nginx.ingress.kubernetes.io/rewrite-target: '/api/v1/write'
spec:
  rules:
  - host: "34.170.3.79.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: "prometheus-server"
            port:
              number: 80
