{
 "title": "Astra DB Metrics",
 "description": "Astra Serverless metrics for reads and writes",
 "tags": [ "public" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "RATE", "label": "Metric Rate", "query": "1m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Request Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Combined",
   "type": "graph",
   "description": "This panel shows request rates (req/s) for different types of requests. The rates are summed over all database coordinators.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "astra_db_read_latency_seconds:rate$RATE{}",
     "legendFormat": "Read"
    },
    {
     "expr": "astra_db_write_latency_seconds:rate$RATE{}",
     "legendFormat": "Write"
    },
    {
     "expr": "astra_db_range_latency_seconds:rate$RATE{}",
     "legendFormat": "Range"
    },
    {
     "expr": "astra_db_rate_limited_requests:rate$RATE{}",
     "legendFormat": "Rate Limited"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "graph",
   "description": "This panel shows the request error rates (req/s) for different types of requests. The rates are summed over all database coordinators.\n - Timeouts indicate that the queries are taking too long to complete.\n - Unavailables indicate that the coordinator did not have enough alive data nodes to work with.\n - Failures can be caused by queries violating certain guardrails or other error conditions. See [<u>Astra DB database guardrails and limits</u>](https://docs.datastax.com/en/astra/docs/datastax-astra-database-limits.html) for more information.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "astra_db_read_requests_failures:rate$RATE{}",
     "legendFormat": "Read Failures"
    },
    {
     "expr": "astra_db_read_requests_timeouts:rate$RATE{}",
     "legendFormat": "Read Timeouts"
    },
    {
     "expr": "astra_db_read_requests_unavailables:rate$RATE{}",
     "legendFormat": "Read Unavailable"
    },
    {
     "expr": "astra_db_write_requests_failures:rate$RATE{}",
     "legendFormat": "Write Failures"
    },
    {
     "expr": "astra_db_write_requests_timeouts:rate$RATE{}",
     "legendFormat": "Write Timeouts"
    },
    {
     "expr": "astra_db_write_requests_unavailables:rate$RATE{}",
     "legendFormat": "Write Unavailable"
    },
    {
     "expr": "astra_db_range_requests_failures:rate$RATE{}",
     "legendFormat": "Range Failures"
    },
    {
     "expr": "astra_db_range_requests_timeouts:rate$RATE{}",
     "legendFormat": "Range Timeouts"
    },
    {
     "expr": "astra_db_range_requests_unavailables:rate$RATE{}",
     "legendFormat": "Range Unavailable"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "description": "This panel shows coordinator write request latency quantiles on the left y-axis, and the total write request rate (req/s) on the right y-axis.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "astra_db_read_latency_seconds:rate$RATE{}",
     "legendFormat": "Write Operations/sec"
    },
    {
     "expr": "astra_db_write_latency_seconds_P99:rate$RATE{}",
     "legendFormat": "P99"
    },
    {
     "expr": "astra_db_write_latency_seconds_P95:rate$RATE{}",
     "legendFormat": "P95"
    },
    {
     "expr": "astra_db_write_latency_seconds_P90:rate$RATE{}",
     "legendFormat": "P90"
    },
    {
     "expr": "astra_db_write_latency_seconds_P75:rate$RATE{}",
     "legendFormat": "P75"
    },
    {
     "expr": "astra_db_write_latency_seconds_P50:rate$RATE{}",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Write Size Distribution",
   "type": "graph",
   "description": "This panel shows different write request mutation size quantiles. Too large mutations can cause performance problems and might even be rejected.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "astra_db_write_requests_mutation_size_bytes_P99:rate$RATE{}",
     "legendFormat": "P99"
    },
    {
     "expr": "astra_db_write_requests_mutation_size_bytes_P95:rate$RATE{}",
     "legendFormat": "P95"
    },
    {
     "expr": "astra_db_write_requests_mutation_size_bytes_P90:rate$RATE{}",
     "legendFormat": "P90"
    },
    {
     "expr": "astra_db_write_requests_mutation_size_bytes_P75:rate$RATE{}",
     "legendFormat": "P75"
    },
    {
     "expr": "astra_db_write_requests_mutation_size_bytes_P50:rate$RATE{}",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "description": "This panel shows coordinator read request latency quantiles on the left y-axis, and the total read request rate (req/s) on the right y-axis.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "astra_db_read_latency_seconds:rate$RATE{}",
     "legendFormat": "Read Operations/sec"
    },
    {
     "expr": "astra_db_read_latency_seconds_P99:rate$RATE{}",
     "legendFormat": "P99"
    },
    {
     "expr": "astra_db_read_latency_seconds_P95:rate$RATE{}",
     "legendFormat": "P95"
    },
    {
     "expr": "astra_db_read_latency_seconds_P90:rate$RATE{}",
     "legendFormat": "P90"
    },
    {
     "expr": "astra_db_read_latency_seconds_P75:rate$RATE{}",
     "legendFormat": "P75"
    },
    {
     "expr": "astra_db_read_latency_seconds_P50:rate$RATE{}",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Range Latency",
   "type": "graph",
   "description": "This panel shows coordinator range request latency quantiles on the left y-axis, and the total range request rate (req/s) on the right y-axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "astra_db_range_latency_seconds:rate$RATE{}",
     "legendFormat": "Range Operations/sec"
    },
    {
     "expr": "astra_db_range_latency_seconds_P99:rate$RATE{}",
     "legendFormat": "P99"
    },
    {
     "expr": "astra_db_range_latency_seconds_P95:rate$RATE{}",
     "legendFormat": "P95"
    },
    {
     "expr": "astra_db_range_latency_seconds_P90:rate$RATE{}",
     "legendFormat": "P90"
    },
    {
     "expr": "astra_db_range_latency_seconds_P75:rate$RATE{}",
     "legendFormat": "P75"
    },
    {
     "expr": "astra_db_range_latency_seconds_P50:rate$RATE{}",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}